# Generated by Django 2.2.1 on 2019-11-26 18:03

import cardosoteste.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=8, validators=[cardosoteste.validators.placa_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='0 minutos', max_length=30)),
                ('paid', models.BooleanField(default=False)),
                ('left', models.BooleanField(default=False)),
                ('entrada', models.DateTimeField(default=datetime.datetime(2019, 11, 26, 18, 3, 43, 743409))),
                ('saida', models.DateTimeField(blank=True, null=True)),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.Car')),
            ],
            options={
                'verbose_name_plural': 'parking',
            },
        ),
    ]
