# Generated by Django 2.2.1 on 2019-11-27 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20191127_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='entrada',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 17, 18, 29, 707914)),
        ),
    ]
