# Generated by Django 2.2.1 on 2019-11-19 19:27

import cardosoteste.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True, validators=[cardosoteste.validators.placa_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.CharField(default='0 minutos', max_length=30)),
                ('pago', models.BooleanField(default=False)),
                ('saiu', models.BooleanField(default=False)),
                ('chegada', models.DateTimeField(default=datetime.datetime(2019, 11, 19, 19, 27, 1, 237297))),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamento.Carro')),
            ],
            options={
                'verbose_name_plural': 'Estacionamento',
            },
        ),
    ]
