# Generated by Django 2.2.1 on 2019-11-20 18:53

import cardosoteste.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True, validators=[cardosoteste.validators.placa_validator])),
                ('tempo', models.CharField(default='0 minutos', max_length=30)),
                ('pago', models.BooleanField(default=False)),
                ('saiu', models.BooleanField(default=False)),
                ('entrada', models.DateTimeField(default=datetime.datetime(2019, 11, 20, 15, 53, 1, 286656))),
                ('saida', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Estacionamento',
            },
        ),
    ]
