# Generated by Django 2.2.1 on 2019-11-20 18:55

import cardosoteste.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamento',
            name='entrada',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 15, 55, 50, 776272)),
        ),
        migrations.AlterField(
            model_name='estacionamento',
            name='placa',
            field=models.CharField(max_length=8, validators=[cardosoteste.validators.placa_validator]),
        ),
    ]
